name: Test deployment

on:
  push:
    branches: [develop]
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.TEST_REGISTRY_ADDRESS }}/vuorovaikutusalusta-test

jobs:
  deploy:
    name: Deploy to test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.TEST_REGISTRY_ADDRESS }}
          username: ${{ secrets.TEST_REGISTRY_USERNAME }}
          password: ${{ secrets.TEST_REGISTRY_PASSWORD }}
      - name: Build
        uses: docker/build-push-action@v5
        with:
          push: true
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline
          tags: ${{ env.IMAGE_NAME }}:latest
